make:
	g++ -std=c++20 -Werror -Wall -pedantic TerminalDisplay.cc TerminalDisplay.h SearchEngine.cc SearchEngine.h BufferToggle.h main.cc -o main
valgrind:
	g++ -std=c++20 -g -Werror -Wall -pedantic TerminalDisplay.cc TerminalDisplay.h SearchEngine.cc SearchEngine.h main.cc -o main

