make:
	g++ -std=c++20 -O3 -pthread -Werror -Wall -pedantic TerminalDisplay.cc TerminalDisplay.h SearchEngine.cc SearchEngine.h BufferToggle.h main.cc -o main
valgrind:
	g++ -std=c++20 -g -O3 -Werror -Wall -pedantic TerminalDisplay.cc TerminalDisplay.h SearchEngine.cc SearchEngine.h main.cc -o main

